[build]
  publish = "."

[[redirects]]
  from = "/*"
  to = "/firstdemo.html"
  status = 200

[context.production]
  environment = { }

[context.deploy-preview]
  environment = { }

[context.branch-deploy]
  environment = { }
